spring:
  application:
    name: money-service
  profiles:
    active: dev  #default profile


  #for avoiding Open-In-View warnings:
  jpa:
    open-in-view: false


#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: money-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: money-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "com.evofun.events"
    listener:
      missing-topics-fatal: false #mb change to TRUE (default)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true


#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never


jwt:
  auth-secret: ${JWT_AUTH_SECRET}
  game-secret: ${JWT_GAME_SECRET}
  system-secret: ${JWT_SYSTEM_SECRET}

game-service:
  base-url: ${GAME_SERVICE_BASE_URL}


