spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}

    locations: classpath:db/migration

    default-schema: money_schema
    schemas: money_schema
    create-schemas: false

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
