spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    url: jdbc:postgresql://money-db:5432/money_db
    user: service_migrator
    password: moneyservicedb_migrator_pass

    locations: classpath:db/migration

    default-schema: money_schema
    schemas: money_schema
    create-schemas: false

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
