spring:
  application:
    name: money-service
  profiles:
    active: dev

  #for avoiding Open-In-View warnings:
  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: money-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "com.evofun.events"
    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

clients:
  services:
    user:
      base-url: ${USER_SERVICE_BASE_URL}
    game:
      base-url: ${GAME_SERVICE_BASE_URL}

jwt:
  secrets:
    user: ${JWT_USER_SECRET}         # user JWT
    internal: ${JWT_INTERNAL_SECRET} # internal JWT (interservice)

security:
  user:
    issuer: ${JWT_USER_ISSUER}
  internal:
    issuer: ${JWT_INTERNAL_ISSUER}
    expected-audience: money-service
    allowed-subjects: user-service,game-service

